# Google Cloud Build configuration untuk deploy ke Cloud Run
# Deploy dengan: gcloud builds submit --config cloudbuild.yaml

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: build
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:latest'
      - '.'
    substitutions:
      _REGION: 'asia-southeast2'  # Jakarta region
      _REPOSITORY: 'indoor-nav'
      _IMAGE_NAME: 'backend'

  # Step 2: Push ke Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: push
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}'
    substitutions:
      _REGION: 'asia-southeast2'

  # Step 3: Deploy ke Cloud Run
  - name: 'gcr.io/cloud-builders/run'
    id: deploy
    args:
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '60s'
      - '--max-instances'
      - '10'
      - '--no-allow-unauthenticated'
      - '--set-env-vars'
      - 'DB_HOST=${_DB_HOST},DB_USER=${_DB_USER},DB_PASSWORD=${_DB_PASSWORD},DB_NAME=${_DB_NAME},SESSION_SECRET=${_SESSION_SECRET},PORT=8080'
    substitutions:
      _REGION: 'asia-southeast2'
      _SERVICE_NAME: 'indoor-nav-backend'
      _DB_HOST: '10.0.0.3'  # Cloud SQL Private IP
      _DB_USER: 'admin'
      _DB_PASSWORD: 'ChangeMe123!'  # Use Secret Manager in production!
      _DB_NAME: 'indoor_navigation'
      _SESSION_SECRET: 'your-secret-key'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:latest'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: 'asia-southeast2'
  _REPOSITORY: 'indoor-nav'
  _IMAGE_NAME: 'backend'
  _SERVICE_NAME: 'indoor-nav-backend'

timeout: '1800s'
